### ISSUE TITLE
Error when running Ember Serve

### ISSUE THREAD

**Issue by sakoh** [mathieul/ember-cli-compass-bootstrap#2]
It installs fine and the generator works just greating, but when I run the <code>ember serve</code>
the file breaks and gives this error:
`
Livereload server on port 35729 <br />
Serving on http://0.0.0.0:4200 <br />
Attempting to watch missing directory: bower_components/bootstrap-sass-official/assets/stylesheets
<font color='red'>Error: Attempting to watch missing directory: bower_components/bootstrap-sass-official/assets/stylesheets</font>
    at EventEmitter.Watcher_addWatchDir [as addWatchDir] (/Applications/AMPPS/www/prayershield/client/node_modules/ember-cli/node_modules/broccoli-sane-watcher/index.js:62:11)
`

Can you fix the watchers so it can look for the files in `vendor` instead of in `bower_components`?

**Comment by mathieul** [comment]
It's probably too late for you, but I fixed the problem in #0.0.6 by using ember-cli `bowerDirectory` instead of hard-coding `bower_components`. Note that I've also documented an alternative to using this package in the README file.
